[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
diesel = { version = "2.2.0", features = ["postgres","chrono"]}
dotenvy = "0.15.7"
uuid = {version = "1.17.0", features = ["v4"]}
argon2 = "0.5.3"
rand_core = "0.10.0"